name: Deployment pipeline

env:
  REPO_OR_PR_LINK: ${{ github.event.pull_request.html_url || github.repository }}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  commit-message-check:
    runs-on: ubuntu-20.04
    outputs:
      should_deploy_or_release: |
        ${{ steps.check_skip_tag.outputs.should_deploy_or_release }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"
      - name: Check for "#skip" tag
        id: check_skip_tag
        run: |
          LAST_COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          if [[ $LAST_COMMIT_MESSAGE == *"#skip"* ]]; then
            echo "should_deploy_or_release=false" >> $GITHUB_OUTPUT
          else
            echo "should_deploy_or_release=true" >> $GITHUB_OUTPUT
          fi

  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    needs: commit-message-check
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Build success
        uses: Ilshidur/action-discord@0c4b27844ba47cb1c7bee539c8eead5284ce9fa9
        if: success()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: "Build succeeded for ${{ env.REPO_OR_PR_LINK }}"
      - name: Build failure
        uses: Ilshidur/action-discord@0c4b27844ba47cb1c7bee539c8eead5284ce9fa9
        if: failure()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: "Build failed for ${{ env.REPO_OR_PR_LINK }}"
      - name: Check style
        run: npm run eslint
      - name: Linting success
        uses: Ilshidur/action-discord@0c4b27844ba47cb1c7bee539c8eead5284ce9fa9
        if: success()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: "Linting passed for ${{ env.REPO_OR_PR_LINK }}"
      - name: Linting failure
        uses: Ilshidur/action-discord@0c4b27844ba47cb1c7bee539c8eead5284ce9fa9
        if: failure()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: "Linting failed for ${{ env.REPO_OR_PR_LINK }}"
      - name: Test
        run: npm test
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: End-to-end tests
        run: npm run test:e2e
      - name: Test success
        uses: Ilshidur/action-discord@0c4b27844ba47cb1c7bee539c8eead5284ce9fa9
        if: success()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: "Test passed for ${{ env.REPO_OR_PR_LINK }}"
      - name: Test failure
        uses: Ilshidur/action-discord@0c4b27844ba47cb1c7bee539c8eead5284ce9fa9
        if: failure()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: "Test failed for ${{ env.REPO_OR_PR_LINK }}"
      - name: Trigger deployment
        if: ${{ github.event_name == 'push' && needs.commit-message-check.outputs.should_deploy_or_release == 'true' }}
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
      - name: Deployment success
        uses: Ilshidur/action-discord@0c4b27844ba47cb1c7bee539c8eead5284ce9fa9
        if: ${{ github.event_name == 'push' && needs.commit-message-check.outputs.should_deploy_or_release == 'true' && success() }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: "New deployment succeeded for ${{ env.REPO_OR_PR_LINK }}"
      - name: Deployment failure
        uses: Ilshidur/action-discord@0c4b27844ba47cb1c7bee539c8eead5284ce9fa9
        if: ${{ github.event_name == 'push' && needs.commit-message-check.outputs.should_deploy_or_release == 'true' && failure() }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: "Deployment failed for ${{ env.REPO_OR_PR_LINK }}"

  tag_release:
    needs:
      - simple_deployment_pipeline
      - commit-message-check
    if: ${{ github.event_name == 'push' && needs.commit-message-check.outputs.should_deploy_or_release == 'true'}}
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@f278d49d30cdd8775cc3e7dd00b5ee11686ee297
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          WITH_V: true
      - name: Version update success
        uses: Ilshidur/action-discord@0c4b27844ba47cb1c7bee539c8eead5284ce9fa9
        if: success()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: "Version updated successfully for ${{ env.REPO_OR_PR_LINK }}"
      - name: Version update failure
        uses: Ilshidur/action-discord@0c4b27844ba47cb1c7bee539c8eead5284ce9fa9
        if: failure()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: "Version update failed for ${{ env.REPO_OR_PR_LINK }}"
